// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"time"
)

type Feed struct {
	ID              string     `json:"id"`
	FeedPartitionID string     `json:"feed_partition_id"`
	PodcasterID     string     `json:"podcaster_id"`
	Published       time.Time  `json:"published"`
	Updated         *time.Time `json:"updated"`
	AddedAt         time.Time  `json:"added_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

type FeedPartition struct {
	ID               string     `json:"id"`
	FeedPartitionUrl string     `json:"feed_partition_url"`
	PodcasterID      string     `json:"podcaster_id"`
	Etag             *string    `json:"etag"`
	LastModified     *time.Time `json:"last_modified"`
	AddedAt          time.Time  `json:"added_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
}

type Podcaster struct {
	ID             string    `json:"id"`
	FeedUrl        string    `json:"feed_url"`
	WebsiteUrl     string    `json:"website_url"`
	Description    *string   `json:"description"`
	ThumbnailImage *string   `json:"thumbnail_image"`
	IsActive       bool      `json:"is_active"`
	IsAuthRequired *bool     `json:"is_auth_required"`
	IsPaid         *bool     `json:"is_paid"`
	AddedAt        time.Time `json:"added_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
