// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: podcaster.sql

package db

import (
	"context"
)

const countPodcasters = `-- name: CountPodcasters :one
SELECT count(*) FROM podcasters
`

func (q *Queries) CountPodcasters(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPodcasters)
	var count int64
	err := row.Scan(&count)
	return count, err
}
